"""
SQL templates for AI Query. SQL is defined here and never generated by the LLM.
"""

from __future__ import annotations

from typing import Any, Dict

from utils.ai_query_plan import plan_to_dict


QUERY_TEMPLATES: dict[str, dict[str, Any]] = {
    "gene_lookup": {
        "description": "Look up one gene by ID.",
        "sql": """
            SELECT id, chrom, x1, x2, length, strand
            FROM genes
            WHERE id = :gene
            LIMIT :limit;
        """,
        "required_args": ["gene"],
        "default_args": {"limit": 1},
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "shortest_gene": {
        "description": "Find the shortest gene.",
        "sql": """
            SELECT id, chrom, x1, x2, length, strand
            FROM genes
            ORDER BY length ASC
            LIMIT :limit;
        """,
        "required_args": [],
        "default_args": {"limit": 1},
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "longest_gene": {
        "description": "Find the longest gene.",
        "sql": """
            SELECT id, chrom, x1, x2, length, strand
            FROM genes
            ORDER BY length DESC
            LIMIT :limit;
        """,
        "required_args": [],
        "default_args": {"limit": 1},
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "compare_gene_lengths": {
        "description": "Compare the lengths of two specific genes.",
        "sql": """
            SELECT id, chrom, x1, x2, length, strand
            FROM genes
            WHERE id = :gene_a OR id = :gene_b
            ORDER BY length DESC;
        """,
        "required_args": ["gene_a", "gene_b"],
        "default_args": {},
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "gene_count_by_chromosome": {
        "description": "Count genes on a chromosome.",
        "sql": """
            SELECT chrom, COUNT(*) AS gene_count
            FROM genes
            WHERE chrom = :chromosome
            GROUP BY chrom;
        """,
        "required_args": ["chromosome"],
        "default_args": {},
        "result_kind": "scalar",
        "visualization_kind": "none",
    },
    "gene_distribution_by_chromosome": {
        "description": "Show the number of genes on each chromosome.",
        "sql": """
            SELECT chrom, COUNT(*) AS gene_count
            FROM genes
            GROUP BY chrom
            ORDER BY
                CASE
                    WHEN chrom = 'chrX' THEN 23
                    WHEN chrom = 'chrY' THEN 24
                    ELSE CAST(REPLACE(chrom, 'chr', '') AS INTEGER)
                END;
        """,
        "required_args": [],
        "default_args": {},
        "result_kind": "distribution",
        "visualization_kind": "bar_chart",
    },
    "phenotype_filter": {
        "description": "List samples matching phenotype, child/parent role, gender, and race filters.",
        "sql": """
            SELECT bam_id, family_id, pheno, child, proband, affected, gender, race
            FROM phenotype
            WHERE (:phenotype IS NULL OR LOWER(pheno) = LOWER(:phenotype))
              AND (:gender IS NULL OR gender = :gender)
              AND (:race IS NULL OR LOWER(race) = LOWER(:race))
              AND (
                    :role = 'any'
                 OR (:role = 'child' AND child = 1)
                 OR (:role = 'parent' AND child = 0)
                 OR (:role = 'mother' AND child = 0 AND gender = 'F')
                 OR (:role = 'father' AND child = 0 AND gender = 'M')
              )
            LIMIT :limit;
        """,
        "required_args": [],
        "default_args": {
            "phenotype": None,
            "gender": None,
            "race": None,
            "role": "any",
            "limit": 50,
        },
        "result_kind": "table",
        "visualization_kind": "none",
    },
    "phenotype_distribution": {
        "description": "Count samples by phenotype.",
        "sql": """
            SELECT pheno, COUNT(*) AS sample_count
            FROM phenotype
            GROUP BY pheno
            ORDER BY sample_count DESC;
        """,
        "required_args": [],
        "default_args": {},
        "result_kind": "distribution",
        "visualization_kind": "bar_chart",
    },
    "race_distribution": {
        "description": "Count samples by race, optionally filtered to OFC/non-normal samples.",
        "sql": """
            SELECT race, COUNT(*) AS sample_count
            FROM phenotype
            WHERE (:phenotype IS NULL OR LOWER(pheno) = LOWER(:phenotype))
            GROUP BY race
            ORDER BY sample_count DESC;
        """,
        "required_args": [],
        "default_args": {"phenotype": None},
        "result_kind": "distribution",
        "visualization_kind": "bar_chart",
    },
    "sex_distribution": {
        "description": "Count samples by sex/gender.",
        "sql": """
            SELECT gender, COUNT(*) AS sample_count
            FROM phenotype
            GROUP BY gender
            ORDER BY sample_count DESC;
        """,
        "required_args": [],
        "default_args": {},
        "result_kind": "distribution",
        "visualization_kind": "bar_chart",
    },
    "sv_filter": {
        "description": "List SVs filtered by sample, chromosome, SV type, and phenotype.",
        "sql": """
            SELECT sample, id AS sv_id, type AS sv_type, chrom, start, "end", length, likelihood, freq, pheno, gender
            FROM phenotype_svs
            WHERE (:sample IS NULL OR sample = :sample)
              AND (:chromosome IS NULL OR chrom = :chromosome)
              AND (:sv_type IS NULL OR type = :sv_type)
              AND (:phenotype IS NULL OR LOWER(pheno) = LOWER(:phenotype))
            ORDER BY chrom, start
            LIMIT :limit;
        """,
        "required_args": [],
        "default_args": {
            "sample": None,
            "chromosome": None,
            "sv_type": None,
            "phenotype": None,
            "limit": 50,
        },
        "result_kind": "table",
        "visualization_kind": "none",
    },
    "sv_type_distribution": {
        "description": "Count SVs by type, optionally grouped by phenotype or gender.",
        "sql": """
            SELECT type AS sv_type, COUNT(*) AS sv_count
            FROM phenotype_svs
            WHERE (:chromosome IS NULL OR chrom = :chromosome)
              AND (:phenotype IS NULL OR LOWER(pheno) = LOWER(:phenotype))
            GROUP BY type
            ORDER BY sv_count DESC;
        """,
        "required_args": [],
        "default_args": {
            "chromosome": None,
            "phenotype": None,
        },
        "result_kind": "distribution",
        "visualization_kind": "bar_chart",
    },
    "svs_contained_in_gene_window": {
        "description": "Find SVs fully contained inside a gene region, optionally expanded by flank_bp.",
        "sql": """
            WITH target_gene AS (
                SELECT id, chrom, x1, x2
                FROM genes
                WHERE id = :gene
                LIMIT 1
            )
            SELECT
                ps.sample AS sample_id,
                ps.id AS sv_id,
                ps.type AS sv_type,
                tg.id AS gene_id,
                tg.chrom AS gene_chrom,
                tg.x1 AS gene_start,
                tg.x2 AS gene_end,
                ps.start AS sv_start,
                ps."end" AS sv_end,
                ps.length AS sv_length,
                ps.likelihood,
                ps.freq
            FROM target_gene tg
            JOIN phenotype_svs ps
                ON ps.chrom = tg.chrom
               AND ps.start >= tg.x1 - :flank_bp
               AND ps."end" <= tg.x2 + :flank_bp
            WHERE (:sv_type IS NULL OR ps.type = :sv_type)
            ORDER BY ps.start
            LIMIT :limit;
        """,
        "required_args": ["gene"],
        "default_args": {
            "sv_type": None,
            "flank_bp": 0,
            "limit": 50,
        },
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "svs_overlapping_gene_window": {
        "description": "Find SVs that overlap a gene region, optionally expanded by flank_bp.",
        "sql": """
            WITH target_gene AS (
                SELECT id, chrom, x1, x2
                FROM genes
                WHERE id = :gene
                LIMIT 1
            )
            SELECT
                ps.sample AS sample_id,
                ps.id AS sv_id,
                ps.type AS sv_type,
                tg.id AS gene_id,
                tg.chrom AS gene_chrom,
                tg.x1 AS gene_start,
                tg.x2 AS gene_end,
                ps.start AS sv_start,
                ps."end" AS sv_end,
                ps.length AS sv_length,
                ps.likelihood,
                ps.freq
            FROM target_gene tg
            JOIN phenotype_svs ps
                ON ps.chrom = tg.chrom
               AND ps.start <= tg.x2 + :flank_bp
               AND ps."end" >= tg.x1 - :flank_bp
            WHERE (:sv_type IS NULL OR ps.type = :sv_type)
            ORDER BY ps.start
            LIMIT :limit;
        """,
        "required_args": ["gene"],
        "default_args": {
            "sv_type": None,
            "flank_bp": 0,
            "limit": 50,
        },
        "result_kind": "table",
        "visualization_kind": "population_igv_gene_window",
    },
    "svs_overlapping_exons": {
        "description": "Find phenotype SVs that overlap one or more exon intervals from the exons table.",
        "sql": """
            SELECT
                ps.sample AS sample_id,
                ps.id AS sv_id,
                ps.type AS sv_type,
                ps.chrom,
                ps.start AS sv_start,
                ps."end" AS sv_end,
                ps.length AS sv_length,
                e.gene_id,
                e.transcript_id,
                e.exon_number,
                e.exon_start,
                e.exon_end
            FROM phenotype_svs ps
            JOIN exons e
                ON e.chrom = ps.chrom
               AND ps.start <= e.exon_end
               AND ps."end" >= e.exon_start
            WHERE (:chromosome IS NULL OR ps.chrom = :chromosome)
              AND (:sample IS NULL OR ps.sample = :sample)
              AND (:sv_type IS NULL OR ps.type = :sv_type)
              AND (:phenotype IS NULL OR LOWER(ps.pheno) = LOWER(:phenotype))
            ORDER BY ps.chrom, ps.start, e.exon_start
            LIMIT :limit;
        """,
        "required_args": [],
        "default_args": {
            "chromosome": None,
            "sample": None,
            "sv_type": None,
            "phenotype": None,
            "limit": 100,
        },
        "result_kind": "table",
        "visualization_kind": "none",
    },
    "family_svs_overlapping_gene_window": {
        "description": "Find family member SVs overlapping a gene window.",
        "sql": """
            WITH target_gene AS (
                SELECT id, chrom, x1, x2
                FROM genes
                WHERE id = :gene
                LIMIT 1
            )
            SELECT
                p.family_id,
                p.bam_id AS sample_id,
                CASE
                    WHEN p.child = 1 THEN 'child'
                    WHEN p.child = 0 AND p.gender = 'F' THEN 'mother'
                    WHEN p.child = 0 AND p.gender = 'M' THEN 'father'
                    ELSE 'parent'
                END AS family_role,
                p.pheno,
                p.affected,
                ps.id AS sv_id,
                ps.type AS sv_type,
                tg.id AS gene_id,
                tg.chrom AS gene_chrom,
                tg.x1 AS gene_start,
                tg.x2 AS gene_end,
                ps.start AS sv_start,
                ps."end" AS sv_end,
                ps.length AS sv_length
            FROM target_gene tg
            JOIN phenotype_svs ps
                ON ps.chrom = tg.chrom
               AND ps.start <= tg.x2 + :flank_bp
               AND ps."end" >= tg.x1 - :flank_bp
            JOIN phenotype p
                ON p.bam_id = ps.sample
            WHERE p.family_id = :family_id
              AND (:sv_type IS NULL OR ps.type = :sv_type)
            ORDER BY family_role, ps.start
            LIMIT :limit;
        """,
        "required_args": ["gene", "family_id"],
        "default_args": {
            "sv_type": None,
            "flank_bp": 0,
            "limit": 100,
        },
        "result_kind": "table",
        "visualization_kind": "family_igv_compare",
    },
}


def get_template_catalog_for_prompt() -> str:
    lines = ["Available query intents:"]
    for name, meta in QUERY_TEMPLATES.items():
        lines.append(f"- {name}: {meta['description']}")
        required = ", ".join(meta.get("required_args", [])) or "none"
        lines.append(f"  required_args: {required}")
    return "\n".join(lines)


def build_sql_from_plan(plan) -> dict[str, Any]:
    if plan.intent not in QUERY_TEMPLATES:
        raise ValueError(f"Unsupported query intent: {plan.intent}")

    template = QUERY_TEMPLATES[plan.intent]
    args: Dict[str, Any] = {}
    args.update(template.get("default_args", {}))

    plan_dict = plan_to_dict(plan)
    for key, value in plan_dict.items():
        if value is not None:
            args[key] = value

    for required in template.get("required_args", []):
        if args.get(required) in (None, ""):
            raise ValueError(f"Missing required argument: {required}")

    return {
        "sql": template["sql"],
        "params": args,
        "intent": plan.intent,
        "result_kind": template.get("result_kind", "table"),
        "visualization_kind": template.get("visualization_kind", "none"),
    }
