"""
Background SV Density page for the UCONN OFC SV Browser.

Reads precomputed run-length-encoded coverage density from
exploration/outputs/background_sv_density/background_sv_density.sqlite and
shows four stacked, synchronized step graphs (DEL, DUP, INV, INS) where the
y-axis is the number of distinct background samples with an SV covering each
coordinate. A dotted horizontal line marks 50 samples as a visual reference;
no data is thresholded.

The density file is generated by:
    PYTHONPATH=. python3 exploration/build_background_sv_density.py
"""

from __future__ import annotations

import csv
import io
import sqlite3
from pathlib import Path

from dash import html, dcc, callback, Input, Output, State, no_update
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from utils.styling import uconn_styles, UCONN_NAVY

DENSITY_DB = Path(__file__).resolve().parents[1] / "exploration" / "outputs" / "background_sv_density" / "background_sv_density.sqlite"
SV_TYPES = ("DEL", "DUP", "INV", "INS")
TYPE_COLORS = {"DEL": "#D64541", "DUP": "#3B7DD8", "INV": "#4CAF50", "INS": "#F2A900"}
THRESHOLD = 50
DEFAULT_CHROM = "chr6"

CHROMOSOMES = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]


def _density_chromosomes() -> list[str]:
    if not DENSITY_DB.is_file():
        return CHROMOSOMES
    conn = sqlite3.connect(f"file:{DENSITY_DB}?mode=ro", uri=True)
    try:
        rows = [row[0] for row in conn.execute("SELECT DISTINCT chrom FROM density ORDER BY chrom")]
    finally:
        conn.close()
    return sorted(rows, key=lambda c: CHROMOSOMES.index(c) if c in CHROMOSOMES else 99) or CHROMOSOMES


def _load_segments(chrom: str) -> dict[str, list[dict]]:
    if not DENSITY_DB.is_file():
        return {}
    conn = sqlite3.connect(f"file:{DENSITY_DB}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    try:
        data: dict[str, list[dict]] = {t: [] for t in SV_TYPES}
        for row in conn.execute(
            'SELECT sv_type, chrom, start, "end", sample_count, sample_fraction FROM density WHERE chrom = ? ORDER BY start',
            (chrom,),
        ):
            data[row["sv_type"]].append(dict(row))
        return data
    finally:
        conn.close()


def _build_figure(chrom: str, y_mode: str) -> go.Figure:
    data = _load_segments(chrom)
    fig = make_subplots(
        rows=len(SV_TYPES),
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.04,
        subplot_titles=[f"{sv_type} deletions" if sv_type == "DEL" else f"{sv_type} insertions" if sv_type == "INS" else f"{sv_type} duplications" if sv_type == "DUP" else f"{sv_type} inversions" for sv_type in SV_TYPES],
        row_heights=[1, 1, 1, 1],
    )

    for i, sv_type in enumerate(SV_TYPES, start=1):
        segments = data.get(sv_type, [])
        if not segments:
            fig.add_trace(go.Scattergl(x=[], y=[], name=sv_type, mode="lines"), row=i, col=1)
            fig.add_hline(y=THRESHOLD, line_dash="dot", line_color="#888888", row=i, col=1)
            continue

        xs = [s["start"] for s in segments]
        ys = [s["sample_count"] for s in segments]
        end_vals = [s["end"] for s in segments]
        frac_vals = [s["sample_fraction"] for s in segments]

        if y_mode == "log":
            keep = [j for j, y in enumerate(ys) if y > 0]
            xs = [xs[j] for j in keep]
            ys = [ys[j] for j in keep]
            end_vals = [end_vals[j] for j in keep]
            frac_vals = [frac_vals[j] for j in keep]

        fig.add_trace(
            go.Scattergl(
                x=xs,
                y=ys,
                name=sv_type,
                mode="lines",
                line=dict(color=TYPE_COLORS[sv_type], width=1.5, shape="hv"),
                customdata=list(zip(end_vals, frac_vals)),
                hovertemplate="<b>%{x:,}</b> - %{customdata[0]:,}<br>"
                "samples: <b>%{y}</b><br>"
                "fraction: %{customdata[1]:.3%}<extra></extra>",
            ),
            row=i,
            col=1,
        )
        fig.add_hline(y=THRESHOLD, line_dash="dot", line_color="#888888", line_width=1, row=i, col=1)

    y_title = "distinct background samples"
    if y_mode == "log":
        y_type = "log"
    elif y_mode == "0-100":
        y_type = "linear"
    else:
        y_type = "linear"

    fig.update_layout(
        height=1200,
        margin=dict(l=80, r=30, t=70, b=50),
        plot_bgcolor="#FFFFFF",
        paper_bgcolor="#FFFFFF",
        hovermode="x unified",
        showlegend=False,
        xaxis4=dict(
            rangeslider=dict(visible=True, thickness=0.08),
            title="Position (hg38)",
        ),
    )

    for i in range(1, len(SV_TYPES) + 1):
        axis_name = "yaxis" if i == 1 else f"yaxis{i}"
        axis = fig.layout[axis_name]
        axis.update(title=dict(text=y_title), type=y_type)
        if y_mode == "0-100":
            axis.update(range=[0, 100])

    fig.update_xaxes(showspikes=True, spikemode="across+marker")
    fig.update_annotations(font_size=13)
    return fig


def page_layout():
    """
    Create the background SV density page layout.

    Returns:
        dash.html.Div: Background SV density page layout
    """
    chromosomes = _density_chromosomes()
    available = DENSITY_DB.is_file()

    if not available:
        return html.Div([
            html.H2('Background SV Density', style={'color': UCONN_NAVY, 'marginBottom': '15px'}),
            html.P(
                'The precomputed density file has not been generated yet. Run:',
                style={'fontSize': '16px', 'lineHeight': '1.5'},
            ),
            html.Pre(
                'PYTHONPATH=. python3 exploration/build_background_sv_density.py',
                style={
                    'backgroundColor': '#f4f4f4',
                    'padding': '12px',
                    'borderRadius': '4px',
                    'fontFamily': 'monospace',
                },
            ),
        ], style={**uconn_styles['content'], 'maxWidth': '1100px', 'margin': '30px auto'})

    return html.Div([
        html.Div([
            html.H2('Background SV Density', style={'color': UCONN_NAVY, 'marginBottom': '15px'}),
            html.P(
                'Number of distinct background samples with a structural variant covering each genomic coordinate. '
                'Each panel is a different SV type. The dotted line marks 50 samples as a reference; no threshold is applied.',
                style={'fontSize': '16px', 'lineHeight': '1.5'},
            ),
        ], style={'marginBottom': '24px'}),

        html.Div([
            html.Div([
                html.Label('Chromosome', style={'fontWeight': 'bold', 'marginBottom': '6px', 'display': 'block'}),
                dcc.Dropdown(
                    id='bg-density-chromosome',
                    options=[{'label': c, 'value': c} for c in chromosomes],
                    value=DEFAULT_CHROM if DEFAULT_CHROM in chromosomes else chromosomes[0],
                    clearable=False,
                ),
            ], style={'width': '240px', 'display': 'inline-block', 'marginRight': '20px', 'verticalAlign': 'top'}),

            html.Div([
                html.Label('Y-axis view', style={'fontWeight': 'bold', 'marginBottom': '6px', 'display': 'block'}),
                dcc.Dropdown(
                    id='bg-density-y-mode',
                    options=[
                        {'label': 'Full range (linear)', 'value': 'linear'},
                        {'label': 'Low counts (0-100)', 'value': '0-100'},
                        {'label': 'Logarithmic', 'value': 'log'},
                    ],
                    value='linear',
                    clearable=False,
                ),
            ], style={'width': '240px', 'display': 'inline-block', 'verticalAlign': 'top'}),

            html.Div([
                html.Button(
                    'Download chromosome CSV',
                    id='bg-density-download-button',
                    n_clicks=0,
                    style={
                        'backgroundColor': UCONN_NAVY,
                        'color': '#FFFFFF',
                        'border': 'none',
                        'padding': '10px 18px',
                        'borderRadius': '4px',
                        'cursor': 'pointer',
                        'marginTop': '26px',
                    },
                ),
                dcc.Download(id='bg-density-download'),
            ], style={'display': 'inline-block', 'verticalAlign': 'top', 'marginLeft': '20px'}),
        ], style={'marginBottom': '18px'}),

        dcc.Loading(
            id='bg-density-loading',
            type='circle',
            children=[
                dcc.Graph(
                    id='bg-density-graph',
                    config={'displayModeBar': True, 'scrollZoom': True},
                    style={'height': '1250px'},
                )
            ],
        ),
    ], style={**uconn_styles['content'], 'maxWidth': '1500px', 'margin': '30px auto'})


@callback(
    Output('bg-density-graph', 'figure'),
    [Input('bg-density-chromosome', 'value'),
     Input('bg-density-y-mode', 'value')],
)
def update_background_sv_density(chrom, y_mode):
    """Update the density graph when chromosome or y-axis mode changes."""
    if not chrom:
        return no_update
    y_mode = y_mode or 'linear'
    return _build_figure(chrom, y_mode)


@callback(
    Output('bg-density-download', 'data'),
    [Input('bg-density-download-button', 'n_clicks')],
    [State('bg-density-chromosome', 'value')],
    prevent_initial_call=True,
)
def download_chromosome_density(n_clicks, chrom):
    """Download all SV-type density segments for the selected chromosome."""
    if not n_clicks or not chrom:
        return no_update
    data = _load_segments(chrom)
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(['sv_type', 'chrom', 'start', 'end', 'sample_count', 'sample_fraction'])
    for sv_type in SV_TYPES:
        for segment in data.get(sv_type, []):
            writer.writerow([
                segment['sv_type'],
                segment['chrom'],
                segment['start'],
                segment['end'],
                segment['sample_count'],
                f"{segment['sample_fraction']:.6f}",
            ])
    return dict(
        content=buffer.getvalue(),
        filename=f"background_sv_density_{chrom}.csv",
        type='text/csv',
    )
